### ISSUE TITLE
A test issue for the tutorial

### ISSUE THREAD

**Issue by gdsc-igdtuw** [GDSC-IGDTUW-Autumn-of-Code-2022/flutter-wordle-app#1]
**Add these dependencies to the `pubspec.yaml` file**

The dependencies should be:
```
dependencies:
  equatable: ^2.0.3
  flip_card: ^0.6.0

  flutter:
    sdk: flutter
```

However, currently they are:

```
dependencies:
  equatable: ^2.0.3
```
